// Catálogo por defecto de productos del taller — usado cuando la BD
// devuelve catálogo vacío. Antes vivía como CATALOGO_BASE en main.js.

export const CATALOGO_BASE = [
  {
    id: 1,
    nombre: "Filipina",
    icono: "👔",
    telas: ["Dacrón", "Dacrón con lycra"],
    colores: ["Blanco", "Azul marino", "Celeste", "Gris", "Negro"],
    modoDefault: "tallas",
    requiereMedidas: false,
    requiereCuello: false,
    camposExtra: [],
    tiempoEst: 3,
    precioBase: null,
    preciosPorTalla: { XS: null, S: null, M: null, L: null, XL: null, "2XL": null, "3XL": null },
    notas: "Confección estándar. Tela dacrón, botones plásticos.",
  },
  {
    id: 2,
    nombre: "Camisa polo",
    icono: "👕",
    telas: ["Dacrón polo", "Piqué", "Jersey"],
    colores: ["Blanco", "Negro", "Azul marino", "Rojo", "Verde"],
    modoDefault: "tallas",
    requiereMedidas: false,
    requiereCuello: true,
    camposExtra: ["colorCuello", "materialCuello"],
    tiempoEst: 3,
    precioBase: null,
    preciosPorTalla: { XS: null, S: null, M: null, L: null, XL: null, "2XL": null, "3XL": null },
    notas: "Incluye cuello tejido. Coordinar con módulo Cuellos.",
  },
  {
    id: 3,
    nombre: "Vestido",
    icono: "👗",
    telas: ["Dacrón", "Satín", "Lino", "Gasa", "Tafeta"],
    colores: ["Blanco", "Negro", "Azul", "Rojo", "Dorado", "Plateado"],
    modoDefault: "lista",
    requiereMedidas: true,
    requiereCuello: false,
    camposExtra: ["ocasion"],
    tiempoEst: 5,
    precioBase: null,
    preciosPorTalla: {},
    notas: "Requiere medidas. Confirmar diseño antes de cortar.",
  },
  {
    id: 4,
    nombre: "Pantalón / Falda",
    icono: "👖",
    telas: ["Dacrón", "Gabardina", "Lino", "Dril"],
    colores: ["Negro", "Azul marino", "Gris", "Café", "Beige"],
    modoDefault: "tallas",
    requiereMedidas: false,
    requiereCuello: false,
    camposExtra: [],
    tiempoEst: 2,
    precioBase: null,
    preciosPorTalla: { XS: null, S: null, M: null, L: null, XL: null, "2XL": null, "3XL": null },
    notas: "",
  },
  {
    id: 5,
    nombre: "Traje / Conjunto",
    icono: "🤵",
    telas: ["Dacrón", "Gabardina", "Lino"],
    colores: ["Negro", "Azul marino", "Gris", "Café"],
    modoDefault: "lista",
    requiereMedidas: true,
    requiereCuello: false,
    camposExtra: ["piezas"],
    tiempoEst: 7,
    precioBase: null,
    preciosPorTalla: {},
    notas: "Especificar piezas del conjunto (saco, pantalón, falda, blusa).",
  },
  {
    id: 6,
    nombre: "Uniforme deportivo",
    icono: "⚽",
    telas: ["Dry-fit", "Lycra", "Jersey deportivo"],
    colores: ["Blanco", "Negro", "Azul", "Rojo", "Verde", "Amarillo"],
    modoDefault: "tallas",
    requiereMedidas: false,
    requiereCuello: false,
    camposExtra: ["numeroDorsal", "nombreDorsal"],
    tiempoEst: 2,
    precioBase: null,
    preciosPorTalla: { XS: null, S: null, M: null, L: null, XL: null, "2XL": null, "3XL": null },
    notas: "Confirmar si lleva número/nombre en espalda (bordado o sublimado).",
  },
  {
    id: 7,
    nombre: "Prenda a la medida",
    icono: "✂️",
    telas: ["Según diseño"],
    colores: ["Según diseño"],
    modoDefault: "lista",
    requiereMedidas: true,
    requiereCuello: false,
    camposExtra: ["diseñoCliente"],
    tiempoEst: 6,
    precioBase: null,
    preciosPorTalla: {},
    notas: "Diseño personalizado. Requiere aprobación de muestra antes de producción.",
  },
  {
    id: 8,
    nombre: "Arreglo / Reparación",
    icono: "🪡",
    telas: [],
    colores: [],
    modoDefault: "tallas",
    requiereMedidas: false,
    requiereCuello: false,
    camposExtra: ["descripcionArreglo"],
    tiempoEst: 1,
    precioBase: null,
    preciosPorTalla: {},
    notas: "Describir el arreglo específico en la descripción del pedido.",
  },
];
